config/routes.rb
Rails.application.routes.draw do
  resources :loans

  resources :quotes do
    member do
      get 'quote_price'
    end
  end
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :customers
  resources :salespeople

  get "inventory/index"
  get "revenue/index"

   root 'home#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :salesperson
  has_one :loan

  def quote_info
    "#{customer.first_name}, $#{final_price}"
  end



  def update_status
    if self.quote_status == true
      car.update_attribute(:car_status,true)
      self.quote_status=:sold

    else
      car.update_attribute(:car_status,false)
      self.quote_status=:unsold

    end
  end

  def final_pri
    self.final_price = (car.cal_markup * 1.043).round(2)
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def quote_price
    logger.info "Call final price of quote"
    quote = Quote.find(params[:id])
    render json: quote
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:salesperson_id, :customer_id, :car_id, :car_price, :sale_tax, :final_price, :quote_status)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salesperson_id %><br>
    <%= f.collection_select :salesperson_id, Salesperson.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :first_name %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select :car_id, Car.all, :id, :model %>
  </div>
    <p>Price of the Car: <span id="markup"></span></p>

  <div class="field">
    <%= f.label :sale_tax %><br>
    <%= f.text_field :sale_tax %>
  </div>
  <div class="field">
    <%= f.label :final_price %><br>
    <%= f.text_field :final_price %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :quote_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote Id</th>
      <th>Salesperson</th>
      <th>Customer</th>
      <th>Car</th>
      <th>Car price</th>
      <th>Sale tax</th>
      <th>Final price</th>
      <th>Quote status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= link_to quote.id, quote_path(quote) %></td>
        <td><%= quote.salesperson.name %></td>
        <td><%= quote.customer.first_name %></td>
        <td><%= quote.car.car_details %></td>
        <td><%= number_to_currency(quote.car.cal_markup) %></td>
        <td><%= number_to_currency(quote.sale_tax) %></td>
        <td><%= number_to_currency(quote.final_pri) %></td>
        <td><%= quote.update_status %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salesperson:</strong>
  <%= @quote.salesperson.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.first_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.model %>
</p>

<p>
  <strong>Car price:</strong>
  <%= number_to_currency(@quote.car_price) %>
</p>

<p>
  <strong>Sale tax:</strong>
  <%= number_to_currency(@quote.sale_tax) %>
</p>

<p>
  <strong>Final price:</strong>
  <%= number_to_currency(@quote.final_pri) %>
</p>

<p>
  <strong>Quote status:</strong>
  <%= @quote.update_status %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>