config/routes.rb
Rails.application.routes.draw do
  resources :loans

  resources :quotes do
    member do
      get 'quote_price'
    end
  end
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :customers
  resources :salespeople

  get "inventory/index"
  get "revenue/index"

   root 'home#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :quote


  #validation
  validates :down_payment ,presence: true
  validates :interest_rate ,presence: true


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:quote_id, :down_payment, :loan_amount, :loan_term, :interest_rate, :monthly_payment)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
  def term
    [
        ['3'], ['4'], ['5']
    ]
  end
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.collection_select :quote_id, Quote.all, :id, :quote_info, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :down_payment %><br>
    <%= f.text_field :down_payment %>
  </div>
  <div class="field">
    <%= f.label :loan_amount %><br>
    <%= f.text_field :loan_amount %>
  </div>
  <div class="field">
    <%= f.label :loan_term %><br>
    <%= f.select :loan_term, options_for_select(term), include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :monthly_payment %><br>
    <%= f.text_field :monthly_payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Loan Id</th>
      <th>Quote</th>
      <th>Down payment</th>
      <th>Loan amount</th>
      <th>Loan term</th>
      <th>Interest rate</th>
      <th>Monthly payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= link_to loan.id, loan_path(loan) %></td>
        <td><%= loan.quote.quote_info %></td>
        <td><%= number_to_currency(loan.down_payment) %></td>
        <td><%= number_to_currency(loan.loan_amount) %></td>
        <td><%= loan.loan_term %></td>
        <td><%= number_to_percentage(loan.interest_rate) %></td>
        <td><%= number_to_currency(loan.monthly_payment) %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @loan.quote.quote_info %>
</p>

<p>
  <strong>Down payment:</strong>
  <%= number_to_currency(@loan.down_payment) %>
</p>

<p>
  <strong>Loan amount:</strong>
  <%= number_to_currency(@loan.loan_amount) %>
</p>

<p>
  <strong>Loan term:</strong>
  <%= @loan.loan_term %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= number_to_percentage(@loan.interest_rate) %>
</p>

<p>
  <strong>Monthly payment:</strong>
  <%= number_to_currency(@loan.monthly_payment) %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>