config/routes.rb
Rails.application.routes.draw do
  resources :loans

  resources :quotes do
    member do
      get 'quote_price'
    end
  end
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :customers
  resources :salespeople

  get "inventory/index"
  get "revenue/index"

   root 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes

  before_save :cal_markup

  validates :model ,presence: true
  validates :color ,presence: true
  validates :vin ,presence: true
  validates :price ,presence: true



  def self.search(search)
    if search
      where('model LIKE ? OR color LIKE ? OR vin LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end

  def car_details
    "#{model}, #{color}"
  end

  def update_status
    if self.car_status == true
      self.car_status=:sold

    else
      self.car_status=:unsold

    end
  end


  def cal_markup
    markup = (self.price * 1.1).round(2)
  end



end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    if params[:search]
      @cars = Car.search(params[:search])
    else
      @cars = Car.all
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def markup
    logger.info "Call markup price"
    car = Car.find(params[:id])
    render json: car
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :color, :vin, :price, :car_status)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :car_status %><br>
    <%= f.check_box :car_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>


<%= form_tag(cars_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Cars" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Car Id</th>
      <th>Model</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Price</th>
      <th>Car status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.price) %></td>
        <td><%= car.update_status %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Car status:</strong>
  <%= @car.car_status %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>